title: Otavio Vargas Resume
url: 'https://vmotavio.github.io/resume/'

description: A resume about Otavio Vargas (Software Engineer)
theme_skin: blue
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

analytics: G-5XX9CZWFY2

sass:
  sass_dir: _sass
  style: compressed
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

port: 4000
host: 0.0.0.0
safe: false